// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0RbXvHXmz6I7JCsCBvht3ceaXW41uZRM',
    appId: '1:107326689456:android:c0528ca805ca868517ab75',
    messagingSenderId: '107326689456',
    projectId: 'whatsapp-buddy-816d6',
    storageBucket: 'whatsapp-buddy-816d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeu_Hs6o_1CRjZHeRK4_N-v3mbbYIhTvU',
    appId: '1:107326689456:ios:52fbd04e1bfbbe0c17ab75',
    messagingSenderId: '107326689456',
    projectId: 'whatsapp-buddy-816d6',
    storageBucket: 'whatsapp-buddy-816d6.appspot.com',
    iosClientId: '107326689456-mppi13v853omd0s9lbeel9nui552mjui.apps.googleusercontent.com',
    iosBundleId: 'com.cal.whatsappbuddy',
  );
}
